import { TealSimStatus, Provider, Sims, PrismaClient } from '@prisma/client';

const testSims: Sims[] = [
  {
    simId: 1,
    userId: 1,
    routerId: 1,
    iccid: 'sim-1',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    eid: 'eid-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,
    provider: Provider.TEAL,
    active: true,
    ipAddress: 'ip-1',
    imei: 'imei-1',
    status: TealSimStatus.ONLINE,
    embedded: true,
    notes: 'This is a cool sim',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    simId: 2,
    userId: 1,
    routerId: 2,
    iccid: '8901990000004842491',
    eid: '89033024108002601600000000853240',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,

    provider: Provider.TEAL,
    active: true,
    ipAddress: '192.198.2.1',
    imei: null,
    status: TealSimStatus.ONLINE,
    embedded: true,
    notes: 'Slide Street LLC',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    simId: 3,
    userId: 1,
    routerId: 3,
    iccid: '8901990000004842509',
    eid: '89033024108002601600000000853337',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,
    provider: Provider.TEAL,
    active: true,
    ipAddress: '192.198.2.1',
    imei: null,
    status: TealSimStatus.ONLINE,
    embedded: true,
    notes: 'Slide Street LLC',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    simId: 4,
    userId: 1,
    routerId: 4,
    iccid: '8901990000004842517',
    eid: '89033024108002601600000000853434',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,
    provider: Provider.TEAL,
    active: true,
    ipAddress: '192.198.2.1',
    imei: null,
    status: TealSimStatus.ONLINE,
    embedded: true,
    notes: 'Slide Street LLC',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    simId: 5,
    userId: 1,
    routerId: 5,
    iccid: '8901990000004842533',
    eid: '89033024108002601600000000853628',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,
    provider: Provider.TEAL,
    active: true,
    ipAddress: '192.198.2.1',
    imei: null,
    status: TealSimStatus.WAITING,
    embedded: true,
    notes: 'Slide Street LLC',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    simId: 6,
    userId: 1,
    routerId: 6,
    iccid: '8901990000004842541',
    eid: '89033024108002601600000000853725',
    imsi: 'imsi-1',
    msisdn: 'msisdn-1',
    ssPlanId: 1,
    tealPlanId: 1,
    planUuid: 'plan-uuid-1',
    planChangeStatus: 'plan-change-status-1',
    planName: 'plan-name-1',
    planPrice: '1.00',
    deviceName: 'device-name-1',
    deviceGroupName: 'device-group-name-1',
    batchNumber: 'batch-number-1',
    bootstrapIccid: 'bootstrap-iccid-1',
    bootstrapImsi: 'bootstrap-imsi-1',
    cap: 2,
    capped: true,
    clientChangeTimestamp: new Date().toDateString(),
    clientId: 1,
    clientName: 'client-name-1',
    clientTitle: 'client-title-1',
    flowType: 'flow-type-1',
    clientUuid: 'client-uuid-1',
    initialBootstrapIccid: 'initial-bootstrap-iccid-1',
    lastConnectedNetwork: 'last-connected-network-1',
    meerkatIpEntries: ['meerkat-ip-entries-1'],
    meerkatPrivateIpEnabled: true,
    meerkatPublicIpEnabled: true,
    planVolumeUnit: 'plan-volume-unit-1',
    profileChangeStatus: 'profile-change-status-1',
    profileOnly: true,
    sku: 'sku-1',
    usage: 1,
    provider: Provider.TEAL,
    active: true,
    ipAddress: '192.198.2.1',
    imei: null,
    status: TealSimStatus.DEACTIVATED,
    embedded: true,
    notes: 'Slide Street LLC',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
]

export default async function seedSims(prisma: PrismaClient) {
  const sims = await prisma.sims.createMany({
    data: testSims,
    skipDuplicates: true,
  });
  console.log(sims);
}